/*----------------------------------------------------------
MASV:
HO TEN CAC THANH VIEN NHOM:
LAB: 03 - NHOM
NGAY:
----------------------------------------------------------*/
--CAU LENH TAO DB
CREATE DATABASE QLSVN
GO

USE QLSVN
GO

alter database QLSVN
set compatibility_level = 120

--CAC CAU LENH TAO TABLE
CREATE TABLE SINHVIEN
(
	MASV VARCHAR(20) PRIMARY KEY,
	HOTEN NVARCHAR(100) NOT NULL,
	NGAYSINH DATETIME,
	DIACHI NVARCHAR(200),
	MALOP VARCHAR(20),
	TENDN NVARCHAR(100) NOT NULL, 
	MATKHAU VARBINARY(2048) NOT NULL
)
GO

CREATE TABLE NHANVIEN
(
	MANV VARCHAR(20) PRIMARY KEY,
	HOTEN NVARCHAR(100) NOT NULL,
	EMAIL VARCHAR(20),
	LUONG VARBINARY(2048),
	TENDN NVARCHAR(100) NOT NULL,
	MATKHAU VARBINARY(2048) NOT NULL,
	PUBKEY VARCHAR(20)
)
GO

CREATE TABLE LOP
(
	MALOP VARCHAR(20) PRIMARY KEY,
	TENLOP NVARCHAR(100) NOT NULL,
	MANV VARCHAR(20)		
)
GO

CREATE TABLE HOCPHAN
(
	MAHP VARCHAR(20) PRIMARY KEY,
	TENHP NVARCHAR(100) NOT NULL,
	SOTC INT
)
GO

CREATE TABLE BANGDIEM
(
	MASV VARCHAR(20),
	MAHP VARCHAR(20),
	DIEMTHI VARBINARY(2048),
	PRIMARY KEY(MASV, MAHP)
)
GO

--CAC CAU LENH TAO KHOA NGOAI
ALTER TABLE SINHVIEN
ADD CONSTRAINT FK_SINHVIEN_LOP FOREIGN KEY(MALOP) REFERENCES LOP(MALOP)
GO

ALTER TABLE LOP
ADD CONSTRAINT FK_LOP_NHANVIEN FOREIGN KEY(MANV) REFERENCES NHANVIEN(MANV)
GO

ALTER TABLE BANGDIEM
ADD CONSTRAINT FK_BANGDIEM_SINHVIEN FOREIGN KEY(MASV) REFERENCES SINHVIEN(MASV)
GO

ALTER TABLE BANGDIEM
ADD CONSTRAINT FK_BANGDIEM_HOCPHAN FOREIGN KEY(MAHP) REFERENCES HOCPHAN(MAHP)
GO

--CAU LENH TAO STORED PROCEDURE
--i) Stored dùng để thêm mới dữ liệu (Insert) vào table NHANVIEN, trong đó
--• Thuộc tính MATKHAU được mã hóa (HASH) sử dụng SHA1
--• Thuộc tính LUONG sẽ được mã hóa từ tham số LUONGCB sử dụng thuật toán RSA
--512, với khóa bí mật là tham số MK được truyền vào.
--• Thuộc tính PUBKEY sẽ lưu trữ tên khóa công khai được tạo ra ứng với nhân viên
--này, giá trị này sẽ = với mã nhân viên.
CREATE PROCEDURE SP_INS_PUBLIC_NHANVIEN @MANV VARCHAR(20),
										@HOTEN NVARCHAR(100),
										@EMAIL VARCHAR(20),
										@LUONGCB INT,
										@TENDN NVARCHAR(100),
										@MK VARCHAR(100)
AS
BEGIN
	--Phần tạo key
	DECLARE @STR NVARCHAR(3000), @AsymID INT
	SET @STR = 'CREATE ASYMMETRIC KEY ' + @MANV + ' WITH ALGORITHM = RSA_512 ENCRYPTION BY PASSWORD = ''' + @MK + ''''
	EXEC (@STR)
	SET @AsymID = ASYMKEY_ID(@MANV)

	INSERT INTO NHANVIEN VALUES(@MANV, @HOTEN, @EMAIL, ENCRYPTBYASYMKEY(@AsymID, CONVERT(VARCHAR, @LUONGCB)), @TENDN, HASHBYTES('SHA1', @MK), @MANV)
END
GO

select * from NHANVIEN

DROP ASYMMETRIC KEY NV01
DROP ASYMMETRIC KEY NV02
GO

DROP PROCEDURE SP_INS_PUBLIC_NHANVIEN
GO

EXEC SP_INS_PUBLIC_NHANVIEN 'NV01', 'NGUYEN VAN A', 'nva@gmail.com', 3000000, 'NVA', '123456'
EXEC SP_INS_PUBLIC_NHANVIEN 'NV02', 'NGUYEN VAN B', 'nvb@gmail.com', 2000000, 'NVB', '1234567'
GO

SELECT * FROM NHANVIEN
GO

DELETE FROM NHANVIEN WHERE MANV = 'NV01'
DELETE FROM NHANVIEN WHERE MANV = 'NV02'
GO

--ii) Stored dùng để truy vấn dữ liệu nhân viên (NHANVIEN)
CREATE PROCEDURE SP_SEL_PUBLIC_NHANVIEN @TENDN NVARCHAR(100), --TENDN ở đây xét vào là MANV chứ không phải cột TENDN
										@MK NVARCHAR(100) --Để NVARCHAR mới có thể bỏ vào hàm DECRYPTBYASYMKEY
AS
BEGIN
	DECLARE @AsymID INT, @LUONG VARBINARY(2048)
	SET @LUONG = (SELECT LUONG FROM NHANVIEN WHERE MANV = @TENDN)
	SET @AsymID = ASYMKEY_ID(@TENDN)

	SELECT MANV, HOTEN, EMAIL, CONVERT(VARCHAR, DECRYPTBYASYMKEY(@AsymID, @LUONG, @MK)) as LUONGCB
	FROM NHANVIEN
	WHERE MANV = @TENDN
END
GO

DROP PROCEDURE SP_SEL_PUBLIC_NHANVIEN
GO

EXEC SP_SEL_PUBLIC_NHANVIEN 'NV01', '123456'
EXEC SP_SEL_PUBLIC_NHANVIEN 'NV02', '1234567'
GO

--Phần viết procedure dùng cho kết nối C#
--Stored procedure dùng cho quá trình đăng nhập
DROP PROCEDURE SP_SIGN_IN
GO

CREATE PROCEDURE SP_SIGN_IN @TENDN NVARCHAR(100), --TENDN ở đây xét vào là MANV chứ không phải cột TENDN
							@MATKHAU VARCHAR(100), 
							@KETQUA INT OUT
AS
BEGIN
	DECLARE @MATKHAUTEMP VARBINARY(2048), @HASHPASS VARBINARY(2048)
	
	--Kiểm tra có tồn tại tên đăng nhập hay không
	IF EXISTS (SELECT * FROM NHANVIEN WHERE MANV = @TENDN)
	BEGIN
		SET @MATKHAUTEMP = HASHBYTES('SHA1', @MATKHAU)
		SET @HASHPASS = (SELECT MATKHAU FROM NHANVIEN WHERE MANV = @TENDN)
		PRINT @MATKHAUTEMP
		PRINT @HASHPASS
		IF (CONVERT(VARCHAR, @MATKHAUTEMP) = CONVERT(VARCHAR, @HASHPASS))
		BEGIN
			PRINT('DANG NHAP THANH CONG')
			SET @KETQUA = 1
		END
		ELSE
		BEGIN
			PRINT('SAI MAT KHAU')
			SET @KETQUA = 0
		END
	END
	ELSE
	BEGIN
		PRINT 'DANG NHAP KHONG HOP LE'
		SET @KETQUA = -1
	END
END
GO

DECLARE @KETQUA INT
EXEC SP_SIGN_IN 'NV01', '123456', @KETQUA OUT
PRINT @KETQUA
GO

--Stored procedure dùng cho quản lý lớp học
CREATE PROCEDURE SP_DANH_SACH_LOP
AS
BEGIN
	SELECT * FROM LOP
END
GO

CREATE PROCEDURE SP_LAY_DS_NV
AS
BEGIN
	SELECT * FROM NHANVIEN
	WHERE MANV NOT IN (SELECT MANV FROM LOP)
END
GO

CREATE PROCEDURE SP_THEM_LOP @MALOP VARCHAR(20),
							 @TENLOP NVARCHAR(100),
							 @MANV VARCHAR(20)		

AS
BEGIN
	INSERT INTO LOP VALUES(@MALOP, @TENLOP, @MANV)
END
GO

--Stored procedure dùng cho quản lý sinh viên
CREATE PROCEDURE SP_INS_SINHVIEN @MASV VARCHAR(20), 
								 @HOTEN NVARCHAR(100), 
								 @NGAYSINH DATETIME, 
								 @DIACHI NVARCHAR(200), 
								 @MALOP VARCHAR(20), 
								 @TENDN NVARCHAR(100), 
								 @MATKHAU VARCHAR(100)
AS
BEGIN
	INSERT INTO SINHVIEN VALUES(@MASV, @HOTEN, @NGAYSINH, @DIACHI, @MALOP, @TENDN, HASHBYTES('MD5', @MATKHAU))
END
GO

DROP PROCEDURE SP_INS_SINHVIEN
GO

EXEC SP_INS_SINHVIEN 'SV01', 'NGUYEN HOANG KIM', '1/1/1990', '280 AN DUONG VUONG', 'CNTT-K35', 'SV01', 'pass123'
EXEC SP_INS_SINHVIEN 'SV02', 'PHAN KHANH LAM', '1/1/1990', '450 AU CO', 'CNTT-K35', 'SV02', 'lam96'
GO

SELECT * FROM SINHVIEN
GO

CREATE PROCEDURE SP_DSSV
AS
BEGIN
	SELECT MASV, HOTEN, NGAYSINH, DIACHI, MALOP, TENDN FROM SINHVIEN
END
GO

CREATE PROCEDURE SP_UPDATE_SV @MASV VARCHAR(20), 
							  @HOTEN NVARCHAR(100),
							  @NGAYSINH DATETIME,
							  @DIACHI NVARCHAR(200),
							  @TENDN NVARCHAR(100)
AS
BEGIN
	IF (@HOTEN = NULL)
		SELECT @HOTEN = HOTEN FROM SINHVIEN WHERE MASV = @MASV
	IF (@NGAYSINH = NULL)
		SELECT @NGAYSINH = NGAYSINH FROM SINHVIEN WHERE MASV = @MASV
	IF (@DIACHI = NULL)
		SELECT @DIACHI = DIACHI FROM SINHVIEN WHERE MASV = @MASV
	IF (@TENDN = NULL)
		SELECT @TENDN = TENDN FROM SINHVIEN WHERE MASV = @MASV

	UPDATE SINHVIEN SET HOTEN = @HOTEN, NGAYSINH = @NGAYSINH, DIACHI = @DIACHI, TENDN = @TENDN
	WHERE MASV = @MASV

END
GO


--Stored procedure dùng cho nhâp điểm sinh viên

--Thêm dữ liệu
INSERT INTO HOCPHAN VALUES('HP01', N'Cơ sở dữ liệu', 4)
INSERT INTO HOCPHAN VALUES('HP02', N'Cơ sở dữ liệu nâng cao', 4)
INSERT INTO HOCPHAN VALUES('HP03', N'Bảo mật cơ sở dữ liệu', 4)
INSERT INTO HOCPHAN VALUES('HP04', N'Tương tác người - máy', 4)
INSERT INTO HOCPHAN VALUES('HP05', N'Phân tích thiết kế HTTT', 4)
INSERT INTO HOCPHAN VALUES('HP06', N'Hệ quản trị CSDL', 4)
INSERT INTO HOCPHAN VALUES('HP07', N'Phát triển ứng dụng HTTT hiện đại', 4)
SELECT * FROM HOCPHAN
GO

EXEC SP_INS_PUBLIC_NHANVIEN 'NV03', 'HO THI THANH TUYEN', 'httt@gmail.com', 3000000, 'HTTT', 'abcd123'
EXEC SP_INS_PUBLIC_NHANVIEN 'NV04', 'TUAN NGUYEN HOAI DUC', 'tnhd@gmail.com', 10000000, 'TNHD', 'abcd123'
EXEC SP_INS_PUBLIC_NHANVIEN 'NV05', 'PHAM MINH TU', 'pmt@gmail.com', 6000000, 'PMT', 'abcd123'
EXEC SP_INS_PUBLIC_NHANVIEN 'NV06', 'LE THI NHAN', 'ltn@gmail.com', 6000000, 'LTN', 'abcd123'
EXEC SP_INS_PUBLIC_NHANVIEN 'NV07', 'LUONG VI MINH', 'lvm@gmail.com', 3000000, 'LVM', 'abcd123'
EXEC SP_INS_PUBLIC_NHANVIEN 'NV08', 'HOANG ANH TU', 'hat@gmail.com', 3000000, 'HAT', 'abcd123'
SELECT * FROM NHANVIEN
GO

INSERT INTO LOP VALUES('LOP01', N'Cơ sở dữ liệu', 'NV01')
INSERT INTO LOP VALUES('LOP02', N'Bảo mật cơ sở dữ liệu', 'NV02')
INSERT INTO LOP VALUES('LOP03', N'Phân tích thiết kế HTTT', 'NV03')
INSERT INTO LOP VALUES('LOP04', N'Tương tác người - máy', 'NV07')
INSERT INTO LOP VALUES('LOP05', N'Phát triển ứng dụng HTTT hiện đại', 'NV06')
INSERT INTO LOP VALUES('LOP06', N'Hệ quản trị CSDL', 'NV05')
INSERT INTO LOP VALUES('LOP07', N'Cơ sở dữ liệu nâng cao', 'NV04')
SELECT * FROM LOP
GO

EXEC SP_INS_SINHVIEN 'SV01', 'NGUYEN HOANG KIM', '1/1/1990', '280 AN DUONG VUONG', 'LOP01', 'SV01', 'pass123'
EXEC SP_INS_SINHVIEN 'SV02', 'PHAN KHANH LAM', '1/1/1990', '450 AU CO', 'LOP01', 'SV02', 'lam96'
EXEC SP_INS_SINHVIEN 'SV03', 'NGUYEN HOANG LAN', '1/1/1990', '280 AN DUONG VUONG', 'LOP02', 'SV03', 'pass123'
EXEC SP_INS_SINHVIEN 'SV04', 'VUONG THIEN PHU', '1/1/1990', '450 AU CO', 'LOP02', 'SV04', 'pass123'
EXEC SP_INS_SINHVIEN 'SV05', 'DANG NHAT MINH', '1/1/1990', '280 AN DUONG VUONG', 'LOP03', 'SV05', 'pass123'
EXEC SP_INS_SINHVIEN 'SV06', 'HUYNH CONG LOI', '1/1/1990', '450 AU CO', 'LOP03', 'SV06', 'pass123'
SELECT * FROM SINHVIEN
GO
