/*----------------------------------------------------------
MASV: 1412274, 1412282, 1412414
HO TEN CAC THANH VIEN NHOM:
	1412274 - Nguyen Hoang Kim
	1412282 - Nguyen Hoang Lan
	1412414 - Vuong Thien Phu
LAB: 03 - NHOM
NGAY: 12/06/2018
----------------------------------------------------------*/
USE QLSVN
GO

--CAU LENH TAO STORED PROCEDURE
--i) Stored dùng để thêm mới dữ liệu (Insert) vào table NHANVIEN, trong đó
--• Thuộc tính MATKHAU được mã hóa (HASH) sử dụng SHA1
--• Thuộc tính LUONG sẽ được mã hóa từ tham số LUONGCB sử dụng thuật toán RSA
--512, với khóa bí mật là tham số MK được truyền vào.
--• Thuộc tính PUBKEY sẽ lưu trữ tên khóa công khai được tạo ra ứng với nhân viên
--này, giá trị này sẽ = với mã nhân viên.
CREATE PROCEDURE SP_INS_PUBLIC_NHANVIEN @MANV VARCHAR(20),
										@HOTEN NVARCHAR(100),
										@EMAIL VARCHAR(20),
										@LUONGCB INT,
										@TENDN NVARCHAR(100),
										@MK VARCHAR(100)
AS
BEGIN
	--Phần tạo key
	DECLARE @STR NVARCHAR(3000), @AsymID INT
	SET @STR = 'CREATE ASYMMETRIC KEY ' + @MANV + ' WITH ALGORITHM = RSA_512 ENCRYPTION BY PASSWORD = ''' + @MK + ''''
	EXEC (@STR)
	SET @AsymID = ASYMKEY_ID(@MANV)

	INSERT INTO NHANVIEN VALUES(@MANV, @HOTEN, @EMAIL, ENCRYPTBYASYMKEY(@AsymID, CONVERT(VARCHAR, @LUONGCB)), @TENDN, HASHBYTES('SHA1', @MK), @MANV)
END
GO

select * from NHANVIEN

DROP ASYMMETRIC KEY NV01
DROP ASYMMETRIC KEY NV02
GO

DROP PROCEDURE SP_INS_PUBLIC_NHANVIEN
GO

EXEC SP_INS_PUBLIC_NHANVIEN 'NV01', 'NGUYEN VAN A', 'nva@gmail.com', 3000000, 'NVA', '123456'
EXEC SP_INS_PUBLIC_NHANVIEN 'NV02', 'NGUYEN VAN B', 'nvb@gmail.com', 2000000, 'NVB', '1234567'
GO

SELECT * FROM NHANVIEN
GO

DELETE FROM NHANVIEN WHERE MANV = 'NV01'
DELETE FROM NHANVIEN WHERE MANV = 'NV02'
GO

--ii) Stored dùng để truy vấn dữ liệu nhân viên (NHANVIEN)
CREATE PROCEDURE SP_SEL_PUBLIC_NHANVIEN @TENDN NVARCHAR(100), --TENDN ở đây xét vào là MANV chứ không phải cột TENDN
										@MK NVARCHAR(100) --Để NVARCHAR mới có thể bỏ vào hàm DECRYPTBYASYMKEY
AS
BEGIN
	DECLARE @AsymID INT, @LUONG VARBINARY(2048)
	SET @LUONG = (SELECT LUONG FROM NHANVIEN WHERE MANV = @TENDN)
	SET @AsymID = ASYMKEY_ID(@TENDN)

	SELECT MANV, HOTEN, EMAIL, CONVERT(VARCHAR, DECRYPTBYASYMKEY(@AsymID, @LUONG, @MK)) as LUONGCB
	FROM NHANVIEN
	WHERE MANV = @TENDN
END
GO

DROP PROCEDURE SP_SEL_PUBLIC_NHANVIEN
GO

EXEC SP_SEL_PUBLIC_NHANVIEN 'NV01', '123456'
EXEC SP_SEL_PUBLIC_NHANVIEN 'NV02', '1234567'
GO


--Thêm dữ liệu
EXEC SP_INS_PUBLIC_NHANVIEN 'NV03', 'HO THI THANH TUYEN', 'httt@gmail.com', 3000000, 'HTTT', 'abcd123'
EXEC SP_INS_PUBLIC_NHANVIEN 'NV04', 'TUAN NGUYEN HOAI DUC', 'tnhd@gmail.com', 10000000, 'TNHD', 'abcd123'
EXEC SP_INS_PUBLIC_NHANVIEN 'NV05', 'PHAM MINH TU', 'pmt@gmail.com', 6000000, 'PMT', 'abcd123'
EXEC SP_INS_PUBLIC_NHANVIEN 'NV06', 'LE THI NHAN', 'ltn@gmail.com', 6000000, 'LTN', 'abcd123'
SELECT * FROM NHANVIEN
GO

EXEC SP_INS_SINHVIEN 'SV01', 'NGUYEN HOANG KIM', '1/1/1990', '280 AN DUONG VUONG', 'LOP01', 'SV01', 'pass123'
EXEC SP_INS_SINHVIEN 'SV02', 'PHAN KHANH LAM', '1/1/1990', '450 AU CO', 'LOP01', 'SV02', 'lam96'
EXEC SP_INS_SINHVIEN 'SV03', 'NGUYEN HOANG LAN', '1/1/1990', '280 AN DUONG VUONG', 'LOP02', 'SV03', 'pass123'
EXEC SP_INS_SINHVIEN 'SV04', 'VUONG THIEN PHU', '1/1/1990', '450 AU CO', 'LOP02', 'SV04', 'pass123'
EXEC SP_INS_SINHVIEN 'SV05', 'DANG NHAT MINH', '1/1/1990', '280 AN DUONG VUONG', 'LOP03', 'SV05', 'pass123'
EXEC SP_INS_SINHVIEN 'SV06', 'HUYNH CONG LOI', '1/1/1990', '450 AU CO', 'LOP03', 'SV06', 'pass123'
SELECT * FROM SINHVIEN
GO

INSERT INTO HOCPHAN VALUES('HP01', N'Cơ sở dữ liệu', 4)
INSERT INTO HOCPHAN VALUES('HP02', N'Cơ sở dữ liệu nâng cao', 4)
INSERT INTO HOCPHAN VALUES('HP03', N'Bảo mật cơ sở dữ liệu', 4)
INSERT INTO HOCPHAN VALUES('HP04', N'Tương tác người - máy', 4)
INSERT INTO HOCPHAN VALUES('HP05', N'Phân tích thiết kế HTTT', 4)
INSERT INTO HOCPHAN VALUES('HP06', N'Hệ quản trị CSDL', 4)
INSERT INTO HOCPHAN VALUES('HP07', N'Phát triển ứng dụng HTTT hiện đại', 4)
SELECT * FROM HOCPHAN
GO

INSERT INTO LOP VALUES('14CTT1', N'Lớp hệ chính quy 1', 'NV01')
INSERT INTO LOP VALUES('14CTT2', N'Lớp hệ chính quy 2', 'NV02')
INSERT INTO LOP VALUES('14CTT3', N'Lớp hệ chính quy 3', 'NV03')
INSERT INTO LOP VALUES('14CNTN', N'Lớp cử nhân tài năng', 'NV04')
SELECT * FROM LOP
GO

