/*----------------------------------------------------------
MASV:1412053-1412430-1412544
HO TEN CAC THANH VIEN NHOM:
	1412053	Nguyễn Huyền Quý Châu
	1412430 Nguyễn Vũ Quang
	1412544	Phạm Đức Tiên
LAB: 03 - NHOM
NGAY:31-05-2017
----------------------------------------------------------*/
use QLSVNhom
go

/* CAU LENH TAO STORED PROCEDURE */
/*cau c-i*/ 

CREATE proc SP_INS_PUBLIC_NHANVIEN
	@MANV VARCHAR(20),
	@HOTEN NVARCHAR(100),
	@EMAIL VARCHAR(20),
	@LUONGCB VARCHAR(10),
	@TENDN NVARCHAR(100),
	@MK NVARCHAR(100)
	AS
	BEGIN
	DECLARE @EXECUTE_CMD NVARCHAR(MAX);
	SET @EXECUTE_CMD = 'IF AsymKey_ID('''+ @MANV +''') IS NULL
						BEGIN
							CREATE ASYMMETRIC KEY '+ @MANV +' 
							WITH ALGORITHM = RSA_512
							ENCRYPTION BY PASSWORD ='''+ @MK +''';
						END';
	EXEC(@EXECUTE_CMD);
	DECLARE @MATKHAU_ENCRYPTED VARBINARY(MAX);
	set @MATKHAU_ENCRYPTED = HashBytes('SHA1', @MK);
	DECLARE @LUONG_ENCRYPTED VARBINARY(MAX);
	set @LUONG_ENCRYPTED = EncryptByAsymKey(AsymKey_ID(@MANV),@LUONGCB);/*ma hoa voi khoa maNV*/
	INSERT INTO NHANVIEN(MANV, HOTEN, EMAIL,LUONG,TENDN,MATKHAU,PUBKEY) 
		VALUES ( @MANV, @HOTEN, @EMAIL,@LUONG_ENCRYPTED,@TENDN,@MATKHAU_ENCRYPTED,@MANV);
	END
GO

/*cau c-ii*/
CREATE proc SP_SEL_PUBLIC_NHANVIEN
	@TENDN NVARCHAR(100),
	@MK NVARCHAR(100)
	as
	SELECT MANV, 
		HOTEN, 
		EMAIL,
		CONVERT(VARCHAR,DecryptByAsymKey(AsymKey_ID(NV.MANV), LUONG, @MK)) as 'LUONGCB'
	FROM dbo.NHANVIEN as NV
	WHERE NV.TENDN=@TENDN AND NV.MATKHAU=HashBytes('SHA1', @MK)
go

/*tao proc cho SINHVIEN*/
CREATE proc SP_INS_PUBLIC_SINHVIEN
	@MASV NVARCHAR(20),
	@HOTEN nVARCHAR(100),
	@NGAYSINH DATETIME,
	@DIACHI NVARCHAR(200),
	@MALOP VARCHAR(20),
	@TENDN NVARCHAR(100),
	@MATKHAU VARCHAR(100)
	AS
	BEGIN
	DECLARE @MATKHAU_ENCRYPTED VARBINARY(MAX)
	set @MATKHAU_ENCRYPTED = HashBytes('MD5', @MATKHAU)
	INSERT INTO SINHVIEN(MASV, HOTEN, NGAYSINH,DIACHI,MALOP,TENDN,MATKHAU) 
		VALUES ( @MASV, @HOTEN, @NGAYSINH,@DIACHI,@MALOP,@TENDN,@MATKHAU_ENCRYPTED)
	END
go

CREATE proc SP_UPDATE_PUBLIC_SINHVIEN
	@MASV NVARCHAR(20),
	@HOTEN nVARCHAR(100),
	@NGAYSINH DATETIME,
	@DIACHI NVARCHAR(200),
	@MALOP VARCHAR(20),
	@TENDN NVARCHAR(100),
	@MATKHAU VARCHAR(100)
	AS
	BEGIN
	DECLARE @MATKHAU_ENCRYPTED VARBINARY(MAX)
	set @MATKHAU_ENCRYPTED = HashBytes('MD5', @MATKHAU)
	UPDATE SINHVIEN
	SET HOTEN=@HOTEN, NGAYSINH=@NGAYSINH,DIACHI=@DIACHI,MALOP=@MALOP,TENDN=@TENDN,MATKHAU=@MATKHAU_ENCRYPTED
	WHERE  MASV=@MASV
	END
go


/*cau d*/
EXEC SP_INS_PUBLIC_NHANVIEN 'NV01', 'NGUYEN VAN A', 'nva@yahoo.com', '3000000','NVA', '123456'
EXEC SP_INS_PUBLIC_NHANVIEN 'NV02', 'NGUYEN VAN B', 'nvb@yahoo.com', '2000000','NVB', '1234567'

EXEC SP_SEL_PUBLIC_NHANVIEN 'NVA', '123456'
EXEC SP_SEL_PUBLIC_NHANVIEN 'NVB', '1234567'

UPDATE BANGDIEM SET DIEMTHI=0x2A6CB5E571E493FCE4E6293F3B04E8C9 WHERE BANGDIEM.MAHP='HP1' AND BANGDIEM.MASV='SV01'